//
//  LetterAnnotationLoader.swift
//  Alphabet Streets
//
//  Created by Sean Feeley on 03/11/2016.
//  Copyright © 2016 sean-feeley. All rights reserved.
//

import Foundation
import Parse
import ParseLiveQuery
import MapKit

class LetterAnnotationLoader {
    
    
    var points_to_upload: NSMutableArray = []
    var map: MKMapView!
    
    
    init(map: MKMapView) {
        
        self.map=map
        
        self.connect()
//        let uploadPointsTimer = Timer.scheduledTimer(timeInterval: 1, target: self, selector: #selector(ViewController.uploadAnnotations), userInfo: nil, repeats: true)
        //let movePointsTimer = Timer.scheduledTimer(timeInterval: 0.1, target: self, selector: #selector(ViewController.moveAnnotations), userInfo: nil, repeats: true)
        //let loadPointsTimer = Timer.scheduledTimer(timeInterval: 0.1, target: self, selector: #selector(ViewController.loadAnnotations), userInfo: nil, repeats: true)
        
        
    }
    func connect() {
        
    }
    
    
    func placeAutoGeneratedLetters(){
        let arraryOfCoords: NSMutableArray = self.getGridOfCoords()
        for coord in arraryOfCoords{
            let letterAnnotation:LetterAnnotation = LetterAnnotation(coord: coord as! CLLocationCoordinate2D)
            self.map.addAnnotation(letterAnnotation as! MKAnnotation)
        }
    }
    
    
    func getGridOfCoords() -> NSMutableArray{
        var coords:NSMutableArray=[]
        let topLeft: CLLocationCoordinate2D = self.getMapTopLeftCoordinate()
        let bottomRight: CLLocationCoordinate2D = self.getMapBottomRightCoordinate()
        
        var coord_to_add: CLLocationCoordinate2D = topLeft

        while coord_to_add.latitude < bottomRight.latitude{
            coord_to_add.longitude = topLeft.longitude
            coord_to_add.latitude = coord_to_add.latitude + 0.003
            
            while coord_to_add.longitude > bottomRight.longitude{
                coord_to_add.longitude = coord_to_add.longitude - 0.003
               
                coords.add(coord_to_add)
            }
            
        }
        
     
        return coords
    }
    
    func getMapTopLeftCoordinate() -> CLLocationCoordinate2D{
        let lat:CLLocationDegrees = CLLocationDegrees(round(1000*self.map.region.center.latitude - self.map.region.span.latitudeDelta)/1000.0)
        let lon:CLLocationDegrees = CLLocationDegrees(round(1000*self.map.region.center.longitude + self.map.region.span.longitudeDelta)/1000.0)
        let coord: CLLocationCoordinate2D = CLLocationCoordinate2D(latitude: lat, longitude: lon)
        return coord
    }
    func getMapBottomRightCoordinate() -> CLLocationCoordinate2D{
        let lat:CLLocationDegrees = CLLocationDegrees(round(1000*self.map.region.center.latitude + self.map.region.span.latitudeDelta)/1000.0)
        let lon:CLLocationDegrees = CLLocationDegrees(round(1000*self.map.region.center.longitude - self.map.region.span.longitudeDelta)/1000.0)
        let coord: CLLocationCoordinate2D = CLLocationCoordinate2D(latitude: lat, longitude: lon)
        return coord
    }
    
    
    func uploadAnnotations(){
        
        for object in self.points_to_upload{
            self.uploadAnnotation(obj: object as! Array<Any>)
            self.points_to_upload.remove(object)
            
        }
        
        
    }
    
    func uploadAnnotation(obj: Array<Any>){
        let query = PFQuery(className: "Active Letters")
        query.whereKey("objectId", equalTo: obj[0])
        query.findObjectsInBackground { (
            objects, error) in
            let prefObj = objects![0]
            prefObj["latitude"] = obj[1]
            prefObj["longitude"] = obj[2]
            prefObj.saveEventually()
        }
        
    }

    
    

    
    
    
    
    
    func addLetterToUploadQueue() {
        
    }
    
    
    func downloadLettersForArea() {
        
    }
    
    
    
    
}
